### PR TITLE
Specify Docker repo in CircleCI

### PR DESCRIPTION
**Pull request by liyishuai**
per #58

### CODE REVIEW

**Comment by palmskog** [comment]
This also looks good to me, but it would be good to get confirmation that, e.g., MathComp images have been made to work with some project that uses CircleCI (since I also don't use CircleCI).

**Comment by liyishuai** [comment]
Haven't tested, is there a project I can look at?

**Comment by erikmd** [comment]
A comprehensive example of mathcomp-project using these images in its CI is https://github.com/math-comp/odd-order
(although it does rely on GitHub actions, so it is rather a test/example for PR #58).

I also guess that #61 should be OK,
but if you'd really want to test it with Circle CI on a small project using mathcomp, you could maybe just fork https://github.com/erikmd/docker-coq-github-action-demo and add a `meta.yml` with `circle: true`?

**Comment by palmskog** [comment]
This now needs a small rebase since we the merged support for custom Docker repos for GitHub actions.

With respect to testing this out, why not just take a CircleCI project like ExtLib, and do a draft PR which has the following in `meta.yml` and the generated `.yml` file in `.github/workflows/`:
```
tested_coq_opam_versions:
  - version: '8.8'
  - version: '8.9'
  - version: '8.10'
  - version: '8.11'
  - version: 'dev'
  - version: '1.11.0-coq-8.11'
    repo: 'mathcomp/mathcomp'
```

**Comment by liyishuai** [comment]
Test passed with ExtLib.

**Comment by palmskog** [comment]
OK sounds good, I think we can merge this.

**Pull request merged**
