### PR TITLE
fix compatibility with macOS

### LINKED ISSUE #29: generate.sh not compatible with macOS
https://github.com/coq-community/templates/blob/cb4cced445482f1c8286f5beeb615ef0b105d59f/generate.sh#L9

> mktemp: illegal option -- -

https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x

### PR DESCRIPTION
**Pull request by liyishuai**
Resolve #29

### CODE REVIEW

**Comment by Zimmi48** [comment]
Somehow it looks like the same commit but with a different hash has ended up in master.

**Comment by liyishuai** [comment]
I've dropped LICENSE with a rebase-and-force-push. (Maybe force-pushing should be limited to administrators, as organization members like me might make mistakes.)

**Comment by Zimmi48** [comment]
So, did the macOS fix end up in master accidentally?

>Maybe force-pushing should be limited to administrators, as organization members like me might make mistakes.

We could protect the master branch from force-pushing. I'm not sure there's a way to make this apply to everyone but admins, but force-pushing on public branch is rarely a good idea anyway.

**Comment by liyishuai** [comment]
> So, did the macOS fix end up in master accidentally?

Yes I messed up with my local branches, and this fix is on master branch now.

> > Maybe force-pushing should be limited to administrators, as organization members like me might make mistakes.
> 
> We could protect the master branch from force-pushing. I'm not sure there's a way to make this apply to everyone but admins, but force-pushing on public branch is rarely a good idea anyway.

Or we could be more restricting, that only admins can push to master without a maintainer-reviewed PR.

**Comment by Zimmi48** [comment]
BTW, @liyishuai I've sent you a message on Zulip asking whether you wanted to become an official maintainer of this repo but I now realize that you probably don't use Zulip yet. Please see [this message](https://gitter.im/coq/coq?at=5ece827f778fad0b132cf9fa) regarding how to get access to your account that was migrated from Gitter.

**Pull request closed without merging**
