### PR TITLE
ref: clarify keys with examples

### PR DESCRIPTION
**Pull request by liyishuai**
We should clarify many more keys _e.g._ I don't know how to write `tested_coq_nix_versions` in my `meta.yml`.

Also, the [supported tags](https://github.com/coq-community/docker-coq/wiki#supported-tags) wiki seems outdated after https://github.com/coq-community/docker-base/issues/4#issuecomment-597894289.

### CODE REVIEW

**Comment by Zimmi48** [comment]
> I don't know how to write `tested_coq_nix_versions` in my `meta.yml`.

`version_or_url` can be either a version name already released in nixpkgs (as `'8.10'`) or a URL of the form `https://github.com/coq/coq-on-cachix/tarball/<branchname>` where `<branchname>` can be `master` or a release branch like `v8.12` (typically only used to test a project with branches of Coq that are still in alpha or beta.

**Comment by liyishuai** [comment]
> > I don't know how to write `tested_coq_nix_versions` in my `meta.yml`.
> 
> `version_or_url` can be either a version name already released in nixpkgs (as `'8.10'`) or a URL of the form `https://github.com/coq/coq-on-cachix/tarball/<branchname>`

I can see the Cachix branch names in https://github.com/coq/coq-on-cachix/branches.
Which page lists the available versions in nixpkgs?

**Comment by Zimmi48** [comment]
On this page, at the bottom, there is the list of supported Coq versions (currently, everything between 8.5 and 8.11). The top part of the page is also interesting since it lists the currently packaged libraries that can be specified as dependencies.

**Comment by liyishuai** [comment]
I'm confused by `coq_8_10` and `version = "8.10.2"`. Which one does the `version_or_url: '8.10'` come from?
Feel free to push directly, since I'm not so familiar with Nix.

**Comment by Zimmi48** [comment]
The `'8.10'` syntax is used for convenience. It is transformed into `coqPackages_8_10` in the `default.nix` template.

> Feel free to push directly, since I'm not so familiar with Nix.

OK, let me try.

**Pull request merged**
