### PR TITLE
allow specifying the Docker repo for 'tested_coq_opam_versions' for use in .travis.yml

### PR DESCRIPTION
**Pull request by chdoc**
This PR implements the enhancement proposed in #39

### CODE REVIEW

**Comment by chdoc** [comment]
The linter seems to be unhappy, but it doesn't tell my why it's unhappy: 
`We are currently unable to download the log. Please try again later.`

I used the modified template to generate the current CI setup for `graph-theory`

**Comment by chdoc** [comment]
I fixed the spaces. If I understand correctly then `config.yml` should not be too hard to adapt, because it at least mentions the docker repository. So it should be possible to make this variable local to the various jobs. For `coq-action.yml` the change is probably not local to the the `templates` repository (it doesn't even mention `coqorg/coq`).

**Comment by erikmd** [comment]
Hi @chdoc (Cc @palmskog)
> For coq-action.yml the change is probably not local to the the templates repository (it doesn't even mention coqorg/coq).

the README does not mention the `coqorg/coq` repo because it is subsumed by the `coq_version: _` syntax.
But actually you could from now on, take advantage of the generic [`custom_image: _`](https://github.com/coq-community/docker-coq-action#custom_image) syntax.

E.g. you could update your PR and write something like this (without loss of expressivity) for the `coq-action.yml` template:

```
jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
{{# tested_coq_opam_versions }}
          - '{{ version }}'
{{/ tested_coq_opam_versions }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
{{# submodule }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
{{/ submodule }}
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: '{{ opam_name }}{{^ opam_name }}coq-{{ shortname }}{{/ opam_name }}.opam'
{{! The last-but-one interpolation changes delimiters to avoid interpreting the last one as mustache syntax. }}
        custom_image: {{ repo }}{{^ repo }}coqorg/coq{{/ repo }}{{=<% %>=}}:${{ matrix.coq_version }}
```

**Comment by erikmd** [comment]
@palmskog 

> note that it currently will not work for config.yml, i.e., for the Coq Docker GitHub Action.

actually config.yml is the CircleCI config, not the GitHub action config.
Maybe @liyishuai should have a look as well for `config.yml`?

**Comment by palmskog** [comment]
> actually config.yml is the CircleCI config, not the GitHub action config.
> Maybe @liyishuai should have a look as well for `config.yml`?

Thanks for catching that and for the insights on `custom_image`, we should actually make separate issues to address custom Docker repos/images for CircleCI and GitHub actions, respectively.

However, I don't think we should let that prevent merging of this PR.

**Comment by erikmd** [comment]
@palmskog OK I don't mind.
but in this case, the PR should be renamed to include the "Travis CI" keyword or so, and update the `ref.yml` file (it only use that new entry for `.travis.yml` currently)

**Comment by palmskog** [comment]
> it also seems the `ref.yml` documentation spec should be further updated (the `used: _` field is missing)

Good catch again. @chdoc can you take care of this? I can merge after that when linting passes.

**Comment by chdoc** [comment]
> > it also seems the `ref.yml` documentation spec should be further updated (the `used: _` field is missing)

> Good catch again. @chdoc can you take care of this? I can merge after that when linting passes.

I'm not sure how this `used` field is interpreted. `version` doesn't have one either. Is it "inherited" from `tested_coq_opam_versions`. Should I just add a `used` list (with `- .travis.yml` as only entry) to the `repo` list?

**Comment by palmskog** [comment]
> Should I just add a `used` list (with `- .travis.yml` as only entry) to the `repo` list?

This is at least my interpretation of the `used` list, so please go ahead.

**Pull request merged**
