### PR TITLE
Account for schedule trigger in new Nix workflow.

### LINKED ISSUE #103: Failing simple Nix workflow for scheduled jobs
As first reported by @chdoc, the simple Nix CI workflow currently implemented by the `nix-action.yml.mustache` template currently fails for scheduled (`cron`) jobs. The failures appeared after the changes in #100, and are very likely related. Basically, *all* Nix CI jobs fail with the same message:
```
invalid refspec '+refs/pull//head:refs/remotes/pull//head'
```
One example of a failing job can be found here: https://github.com/coq-community/reglang/actions/runs/1208112337

As a workaround, I [disabled](https://github.com/coq-community/reglang/commit/ec5d2aefa0081314bc55b8fc8f0f503d15af35c7) the Nix CI cronjob for reglang. Probably we should prohibit cronjobs directly in the template until this problem is solved. Or what do you recommend in the short term @Zimmi48?

### PR DESCRIPTION
**Pull request by Zimmi48**
This should normally fix #103 but needs to be tested first.

### CODE REVIEW

**Comment by palmskog** [comment]
The changes are essentially Nix gobbledygook to me. But I can try it out in Huffman with a cronjob (but will take a while).

**Comment by Zimmi48** [comment]
There's no Nix-related code in the change, that's only bash and GitHub Actions magic. Anyway, I've tested it on reglang. It works fine for the `pull_request`, `pull_request_target` and `push` events and I expect it will also work fine for the `schedule` event, but we might want to wait until tomorrow to confirm this.

**Comment by Zimmi48** [comment]
It works fine in reglang.

**Comment by palmskog** [comment]
Can confirm it works in Huffman as well. However, the Nix `master` builds are for some reason building Coq from scratch (e.g., https://github.com/coq-community/huffman/actions/runs/1212001932)

**Comment by Zimmi48** [comment]
The PR fixing the deployment to Cachix from Coq's CI still hasn't been merged. So if your CI is the first coq-community CI to build a particular commit of Coq, it's not surprising that it rebuilds it from scratch. Unfortunately, the Huffman and Reglang schedule pipelines are triggered at the same time, so they cannot take advantage of one of them having built and deployed Coq to Cachix.

**Comment by palmskog** [comment]
I see, which Coq PR is it? Would be good to know so I know where to look instead of asking...

**Comment by Zimmi48** [comment]
That's https://github.com/coq/coq/pull/14723.

**Pull request merged**
